// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd47lPAx4fazsBGVqr3bRhIglR7_NVV9E',
    appId: '1:402806012064:web:6bb25538dedf131246f1c5',
    messagingSenderId: '402806012064',
    projectId: 'apartmentsproject-ed2fd',
    authDomain: 'apartmentsproject-ed2fd.firebaseapp.com',
    storageBucket: 'apartmentsproject-ed2fd.firebasestorage.app',
    measurementId: 'G-1PZEWBZEHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDth_yJEsO9aAWsMOBkFxPbdCEsSm9IqI',
    appId: '1:402806012064:android:85ccf7cd25c2b6d646f1c5',
    messagingSenderId: '402806012064',
    projectId: 'apartmentsproject-ed2fd',
    storageBucket: 'apartmentsproject-ed2fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCY0QvHVK-ot7jLq2TBvCwWqm1a6yATQ',
    appId: '1:402806012064:ios:b7e5d04c9bb714f646f1c5',
    messagingSenderId: '402806012064',
    projectId: 'apartmentsproject-ed2fd',
    storageBucket: 'apartmentsproject-ed2fd.firebasestorage.app',
    iosBundleId: 'com.example.houseRentApp002',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwCY0QvHVK-ot7jLq2TBvCwWqm1a6yATQ',
    appId: '1:402806012064:ios:b7e5d04c9bb714f646f1c5',
    messagingSenderId: '402806012064',
    projectId: 'apartmentsproject-ed2fd',
    storageBucket: 'apartmentsproject-ed2fd.firebasestorage.app',
    iosBundleId: 'com.example.houseRentApp002',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd47lPAx4fazsBGVqr3bRhIglR7_NVV9E',
    appId: '1:402806012064:web:b369e8f0dc6b60b746f1c5',
    messagingSenderId: '402806012064',
    projectId: 'apartmentsproject-ed2fd',
    authDomain: 'apartmentsproject-ed2fd.firebaseapp.com',
    storageBucket: 'apartmentsproject-ed2fd.firebasestorage.app',
    measurementId: 'G-JN1BLGZ51E',
  );
}
